# Generated by Django 4.0.3 on 2022-03-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_order_product_id_pk_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_PK',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_PK',
        ),
    ]
